/// <reference types="next" />
/// <reference types="next/image-types" />

// This file was auto-generated by `next.tar`
// To update it, execute `npx next`
// See: https://github.com/vercel/next.js/pull/59346
